version: '3'

services:
  app:
    image: hubone-docker-dev
    build: .
    ports: 
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./ui:/app/ui
      - ./theme.ts:/app/theme.ts
      - ./HubOneConfig.ts:/app/HubOneConfig.ts