FROM node:18-buster-slim
RUN apt-get update && apt-get install libssl-dev ca-certificates -y

WORKDIR /app

RUN npm install typescript ts-node prisma

COPY prisma ./prisma
RUN npx prisma generate

COPY package.json yarn.lock ./
