FROM node:18-buster-slim
RUN apt-get update && apt-get install libssl-dev ca-certificates -y

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY prisma ./prisma
RUN npx prisma generate

COPY next.config.js ./next.config.js

CMD ["yarn", "dev"]